xgboost:
  learning_rate: 0.2            # Learning rate eta
  max_depth: 12                 # Maximum depth of a tree
  n_estimators: 100             # Number of iterations (trees)
  objective: "binary:logistic"  # Loss function
  tree_method: "hist"           # Histogram tree grow method

log_reg:
  penalty: "l2"                 # Specifies the norm of the penalty
  solver: "liblinear"           # Algorithm to use
  max_iter: 100                 # Number of iterations
