learning_rate: [0.1, 0.2, 0.3]    # Learning rate
max_depth: [8, 10, 12]            # Maximum depth of a tree
n_estimators: [100, 200, 300]     # Number of estimators
gamma: [0]                        # Minimum split loss
lambda: [1]                       # Regularization term
scale_pos_weight: [1]             # Balance between positive and negative weights
min_child_weight: [1]             # Minimum sum of weights of all observations in a child
objective: ["binary:logistic"]    # Loss function
tree_method: ["hist"]             # Histogram tree grow method
